Remove `any` in `IJsonStep` interface `arguments` property
cucumber/cucumber-js pull request #1575
Opened 2021-02-09 23:12 UTC by wafuwafu13

Hi :)
I resolved `TODO`
https://github.com/cucumber/cucumber-js/blob/625fab034eea768bf74f7a46993a57182204ddf6/src/formatter/json_formatter.ts#L53

2021-03-19 08:55 UTC, aurelien-reeves reviewed
Thanks for your contribution! :)

Could someone more experienced with cucumber-js take a look too?
Apart for my comments, it looks pretty good to me

Cc. @davidjgoss

2021-03-19 08:55 UTC, aurelien-reeves commented on src/formatter/json_formatter.ts
> +  arguments?: {} | []
It looks like arguments is always an array
Why having the `{} |`?

2021-03-19 08:55 UTC, aurelien-reeves commented on src/formatter/json_formatter.ts
> +  ): [] | {} {
This method actually always return an array
Why `| {}`?

2021-03-25 21:31 UTC, davidjgoss requested changes
Thanks again for contributing.

To pick up on @aurelien-reeves comments, typing as `{} | []` isn't really any narrower than `any`.

Digging through the code a little, it looks like the value will be an array with each item being a formatter-specific representation of either a doc string or a data table. See the `formatDocString` and `formatDataTable` methods in the same file - I think if you start by getting a specific type on both of those you should be able carry that up from there.

2021-04-26 14:42 UTC, aurelien-reeves commented
Thank you for your contribution
We want stricter typing than what you have proposed

See. https://github.com/cucumber/cucumber/issues/1138 which would apply to cucumber-js too

2021-04-26 14:42 UTC, closed without merging