Use new messages without protobuf dependencies.
cucumber/cucumber-js pull request #1645
Opened 2021-04-20 15:59 UTC by aslakhellesoy

This brings the code uptodate with https://github.com/cucumber/cucumber/pull/1414

First `npm link` every @cucumber/* module we depend on in the monorepo.
Then, `npm link [all the modules]` from this repo.

2021-05-17 14:44 UTC, aslakhellesoy commented
I have released all the `@cucumber/*` libraries and updated the dependencies. No need to do the `npm link` dance described above.

2021-05-17 14:45 UTC, aslakhellesoy commented
I'd like to add support for Markdown before merging this - it should be a small change.

2021-05-18 16:35 UTC, aslakhellesoy commented
This is now ready for review. I don't plan any more changes other than addressing review comments.

2021-05-19 08:01 UTC, aurelien-reeves reviewed
Another big PR 😅

Is there something specific we should take care of?

2021-05-19 08:04 UTC, aslakhellesoy commented on features/cli.md
> +# Command line interface
I'm not sure. What are the benefits of enforcing that extension?

2021-05-19 08:04 UTC, davidjgoss requested changes
Changes LGTM in general. Few bits:

- A `package-lock.json` file has shown up here - we're currently using yarn for this project though. I pushed an updated `yarn.lock` after installing locally, suggest we remove and gitignore the npm lockfile until/unless we switch to using npm.
- We have multiple versions of `messages` and `message-streams`, this looks to be due to `gherkin` still depending on an older `message-streams` - see below. Topic for another day, but it might be worth looking at whether we can use `peerDependencies` to reduce the need to basically release everything when certain packages change?
- We seem to be scanning for `*.md` files - did we change from the default convention being `*.feature.md`?

Output of `yarn why @cucumber/message-streams`:

```
yarn why v1.22.10
[1/4] 🤔  Why do we have the module "@cucumber/message-streams"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "@cucumber/message-streams@2.0.0"
info Has been hoisted to "@cucumber/message-streams"
info Reasons this module exists
   - Specified in "devDependencies"
   - Hoisted from "@cucumber#gherkin-streams#@cucumber#message-streams"
info Disk size without dependencies: "384KB"
info Disk size with unique dependencies: "932KB"
info Disk size with transitive dependencies: "3.19MB"
info Number of shared dependencies: 3
=> Found "@cucumber/gherkin#@cucumber/message-streams@1.0.0"
info This module exists because "@cucumber#gherkin" depends on it.
info Disk size without dependencies: "1.89MB"
info Disk size with unique dependencies: "10.04MB"
info Disk size with transitive dependencies: "13.71MB"
info Number of shared dependencies: 5
✨  Done in 0.54s.
```

2021-05-19 08:07 UTC, aslakhellesoy commented
Thanks @davidjgoss - I'll have a look at fixing the dependencies and also removing `package-lock.json`.

2021-05-19 08:07 UTC, davidjgoss commented on features/cli.md
> +# Command line interface
From the discussion the other day it was that:

- We'd avoid collecting Markdown files that weren't intended as specs for Cucumber e.g. readmes or whatever
- Tools like IDEs could use this convention to look for steps in `.feature.md` files and offer completion and quick-run features like they do for feature files

Users could always specify the glob differently themselves, as many do.

2021-05-19 08:11 UTC, aurelien-reeves commented on features/cli.md
> +# Command line interface
For a human, from just reading the file name, we know that this should be an executable spec in addition of some documentation

2021-05-19 08:14 UTC, aslakhellesoy commented on features/cli.md
> +# Command line interface
That's a good point. IIRC, @mpkorstanje also suggested that using `.feature.md` could protect against accidentally picking up Markdown files without any Gherkin in it.

I'll change it.

2021-05-24 16:38 UTC, aslakhellesoy commented on features/cli.md
> +# Command line interface
Fixed - it's looking for `.feature.md` by default now

2021-05-24 16:52 UTC, davidjgoss approved these changes

2021-05-24 16:56 UTC, merged